### ISSUE TITLE
显示有问题，无法查看完整翻译

### ISSUE THREAD

**Issue by qihaogithub** [grover572/obsidian-Dictionary-translator#1]
![iShot_2024-07-30_16 19 40](https://github.com/user-attachments/assets/da0d97b0-d728-4a3b-9b5f-91a5ad53a404)
![image](https://github.com/user-attachments/assets/b65633dd-434c-46ff-99f4-9f87195ea170)

请问这是什么原因呢，显示有问题，内容没有演示中的完整

**Comment by grover572** [comment]
可以提供下Obsidian版本吗

**Comment by 6V836sX** [comment]
translator-card-callout笔记本统一存放吗？现在添加到笔记以后，是存在了添加单词的所在页面，没有集中统一管理，不方便复习。

**Comment by grover572** [comment]
@6V836sX 插件的初衷还是为了查阅笔记的时候能快速复习单词的读音和释义，后面可能会做成单词本的形式

**Comment by grover572** [comment]
@qihaogithub 问题应该是网易的文本翻译接口停止返回了字典相关字段，所以导致插件展现不够丰满，现在正寻找价格合适的字典接口~

**Comment by 6V836sX** [comment]
单词本有利于复习，现在还是用有道词典桌面版，收藏以后可以复习。但obsidian的最大优势是集成度高，稍加一个记忆频率就可以当背单词的单词本。

**Comment by grover572** [comment]
@6V836sX 确实是个好建议，最开始有这样想过，但是其实要做的好一些的话考虑的还是挺多的，例如重复单词的处理，单词如何排序之类的，有兴趣的话可以一起交流迭代下？哈哈

**Comment by 6V836sX** [comment]
可以参考下youtube上将obsidian当单词本导入到anki的逻辑，重复单词直接忽略，用户认为已经熟悉了，就直接点已学会，下次不在出现。单词排序就按加入单词本的时间排序，先进先出pipe
out，符合记忆习惯。有人用再说自定义记忆。集成到obsidian主要图一个集成性，做笔记同时复习，导入导出到anki太麻烦哈哈，不过也看用户量有多大了，为爱发电
